### ISSUE TITLE
Rakudo should detect multi sub duplicates at compile time

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#1455]
Migrated from [rt.perl.org#71536](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=71536) (status was 'open')

Searchable as RT71536$

**Comment by JJ** [comment]
2020.05 is pretty much the same.

```
Ambiguous call to 'f(Int)'; these signatures all match:
:($a)
:($a)
  in block <unit> at -e line 1
```

It's probably calling for a problem solving ticket...

**Comment by masak** [comment]
> It's probably calling for a problem solving ticket...

Yes, probably.

To me, it falls in the same category as other "oopsie" mistakes that we could detect at compile time:

* use of a variable without declaring it
* declaring an (only) sub and then calling it with impossible arguments
* putting a `return` on the top level where there's no routine to return from

All these (and the current issue) share the following sentiment: "this would _definitely_ fail at runtime (as soon as you hit that line), so we fail you now, at comile time, because we're nice that way and we don't want you to waste an iteration cycle that will surely fail".

**Comment by JJ** [comment]
The related problem-solving ticket was closed, this is still an issue. Probably something to be solved in the RakuAST branch?

**Comment by JJ** [comment]
This is the very first issue still open in the old issue tracker. Is there any attempt to solve it using RakuAST?

**Comment by lizmat** [comment]
Not yet, perhaps create a new issue for this and mark it with RakuAST ?

**Comment by JJ** [comment]
I'm not even sure it could be solved that way...

**Comment by lizmat** [comment]
Pretty sure it can  :-)

**Comment by JJ** [comment]
Closing in favor of rakudo/rakudo#5455
