### ISSUE TITLE
dylib statically linked to absolute path

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#2700]
Migrated from [rt.perl.org#112262](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=112262) (status was 'new')

Searchable as RT112262$

**Comment by usev6** [comment]
I've stumbled upon this very old issue, that still refers to Parrot. I'll close this issue, since support for the Parrot backend has been dropped several years ago. (If the same kind of problem should still be relevant for MoarVM, a new issue should be opened over at https://github.com/rakudo/rakudo/issues or at https://github.com/rakudo/star/issues.)
