### ISSUE TITLE
Unneeded rebuilds on rakudo-moar

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3474]
Migrated from [rt.perl.org#122649](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=122649) (status was 'open')

Searchable as RT122649$

**Comment by usev6** [comment]
I think this doesn't happen anymore:
```
$ gmake
+++ Checking for moar NQP version
$ gmake
+++ Checking for moar NQP version
```

No files were updated after these commands. Probably it was fixed with switching to https://github.com/Raku/nqp-configure.

I don't think we need a test for this (and I have no idea how such a test could look like). If you don't agree, please reopen. Closing now.
