### ISSUE TITLE
coercive type constraint for variable inconsistently accepted

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4558]
Migrated from [rt.perl.org#126111](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126111) (status was 'open')

Searchable as RT126111$

**Comment by usev6** [comment]
If I'm not mistaken, coercive type constraints for variables do work now. (Fixed by @vrurg in the context of https://github.com/Raku/problem-solving/issues/227.)

```
$ ./rakudo-m -e 'my Int() $a; $a = 3; say $a; dd $a'
3
Int $a = 3
$ ./rakudo-m -e 'my $a of Int(); $a = 3; say $a; dd $a'
3
Int $a = 3
$ ./rakudo-m -e 'my Int() $a; $a = "04"; say $a; dd $a'
4
Int $a = 4
$ ./rakudo-m -e 'my $a of Int(); $a = "04"; say $a; dd $a'
4
Int $a = 4
$ ./rakudo-m -e 'my Int() $a; $a = "foo"; say $a; dd $a'
Cannot convert string to number: base-10 number must begin with valid digits or '.' in '⏏foo' (indicated by ⏏)
  in block <unit> at -e line 1
$ ./rakudo-m -e 'my $a of Int(); $a = "foo"; say $a; dd $a'
Cannot convert string to number: base-10 number must begin with valid digits or '.' in '⏏foo' (indicated by ⏏)
  in block <unit> at -e line 1
```

We have a very similar test in roast: https://github.com/Raku/roast/blob/2b556e0aac/S12-coercion/coercion-types.t#L68-L75 (unfudged with https://github.com/Raku/roast/commit/4718d3e1ef, was skipped before). That test uses ```my Int(Any) $x```. IMHO it wouldn't hurt to add tests for ```my Int() $x```.

Tagging 'testneeded'

**Comment by vrurg** [comment]
This case is already covered by S12-coercion/coercion-types.t. It's ok to close the issue.
