### ISSUE TITLE
definedness constraints ignored where not supported

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4571]
Migrated from [rt.perl.org#126126](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126126) (status was 'new')

Searchable as RT126126$

**Comment by usev6** [comment]
Current behavior looks good:
```
$ ./rakudo-m -e 'say 3.isa(Mu:U)'
False
$ ./rakudo-m -e 'my Mu:U $a; say "alive"; $a = 4'
alive
Type check failed in assignment to $a; expected Mu:U but got Int (4)
  in block <unit> at -e line 1
```

According to ```bisectable6``` (https://colabti.org/irclogger/irclogger_log/raku-dev?date=2023-10-10#l81) the problem was fixed shortly after this report came in with https://github.com/rakudo/rakudo/commit/80a3d07235.

There is a bunch of tests in [S04-declarations/smiley.t](https://github.com/Raku/roast/blob/master/S04-declarations/smiley.t). (Many of them have been added in October 2015.) I believe this bug report is covered by those tests, so I'm closing it as "resolved" without adding more tests.
