### ISSUE TITLE
CompUnit::Repository::Installation.files appears to be broken

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4820]
Migrated from [rt.perl.org#126806](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126806) (status was 'new')

Searchable as RT126806$

**Comment by usev6** [comment]
Just for the record, this is probably the stable link to the relevant line: https://github.com/rakudo/rakudo/blob/104623a21a/src/core/CompUnit/Repository/Installation.pm#L198

The whole class ```CompUnit::Respository::Installation``` has been changed a lot over the last years.

I can't reproduce the error with a current Rakudo. (I've added a conditional to the last ```say```, because there would be an error that ```CompUnit::Repository::AbsolutePath``` doesn't have a method ```files```.)
```
$ ./rakudo-m -e 'for $*REPO.repo-chain -> $v { say $v.raku; say $v.files("foo").raku if $v.isa(CompUnit::Repository::Installation) }'
CompUnit::Repository::Installation.new(prefix => "/home/christian/.raku")
Empty
CompUnit::Repository::Installation.new(prefix => "/path/to/rakudo.moar/gen/build_rakudo_home/site")
Empty
CompUnit::Repository::Installation.new(prefix => "/path/to/rakudo.moar/gen/build_rakudo_home/vendor")
Empty
CompUnit::Repository::Installation.new(prefix => "//path/to/rakudo.moar/gen/build_rakudo_home/core")
Empty
CompUnit::Repository::AbsolutePath.new(next-repo => CompUnit::Repository::NQP.new(next-repo => CompUnit::Repository::Perl5.new(next-repo => CompUnit::Repository)))
CompUnit::Repository::NQP.new(next-repo => CompUnit::Repository::Perl5.new(next-repo => CompUnit::Repository))
CompUnit::Repository::Perl5.new(next-repo => CompUnit::Repository)
```

IMHO this is closable without adding a test. If you think otherwise, please reopen (or ideally add such a test).

**Comment by jonathanstowe** [comment]
As you say there is a lot of water under the bridge since then.  With the application of a `?`on the call to `files` then it works fine now.
