### ISSUE TITLE
Shaped array in signatures doesn't declare the lexical variable

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5011]
Migrated from [rt.perl.org#127195](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127195) (status was 'new')

Searchable as RT127195$

**Comment by usev6** [comment]
This works now:
```
$ ./rakudo-m -e 'sub foo (@bar[2]) { say "can haz bar: @bar[]" }; my @x[2] = [1,2,3;4,5,6]; foo(@x)'
can haz bar: 1 2 3 4 5 6
```

According to ```bisectable6``` (https://colabti.org/irclogger/irclogger_log/raku-dev?date=2023-10-14#l176) this has been fixed with https://github.com/rakudo/rakudo/commit/ca78390ecc.

The issue mentioned in that commit (https://github.com/rakudo/rakudo/issues/3314) describes the same problem.

We also have a test in roast (added with https://github.com/Raku/roast/commit/ecdf550c86), so I'm closing this issue as "resolved".
