### ISSUE TITLE
mkdir($file) succeeds if $file exists and is a regular file

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5193]
Migrated from [rt.perl.org#127772](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127772) (status was 'open')

Searchable as RT127772$

**Comment by usev6** [comment]
Some more discussion about ```mkdir```'s behaviour can be found here: https://github.com/rakudo/rakudo/issues/1357

**Comment by usev6** [comment]
I also think that ```mkdir($file)``` should signal a failure if there is already a file with that name.

It doesn't do this on current MoarVM:
```
$ : >a-file; ./rakudo-m -e 'my $res := mkdir("a-file"); dd $res'; ls -l a-file
IO::Path.new("a-file", :SPEC(IO::Spec::Unix), :CWD("/path/to/pwd"))
-rw-r--r--  1 christian  christian  0 Apr 11 19:05 a-file
```

On the JVM backend ```mkdir``` returns a failure:
```
$ : >a-file; ./rakudo-j -e 'my $res := mkdir("a-file"); dd $res'; ls -l a-file
Failure.new(exception => X::IO::Mkdir.new(path => "/path/to/pwd/a-file", mode => 511, os-error => "File /path/to/pwd/a-file already exists"), backtrace => Backtrace.new)
-rw-r--r--  1 christian  christian  0 Apr 11 19:10 a-file
```

**Comment by usev6** [comment]
I believe this has been fixed by now:

```
$ : >a-file; ./rakudo-m -e 'my $res := mkdir("a-file"); dd $res'; ls -l a-file
Failure.new(exception => X::IO::Mkdir.new(path => "/path/to/pwd/a-file", mode => 511, os-error => "Failed to mkdir: File exists"), backtrace => Backtrace.new)
-rw-r--r--  1 christian  christian  0 Nov 23 19:50 a-file
```

Fix for MoarVM:  https://github.com/MoarVM/MoarVM/pull/1507 (with two follow ups: https://github.com/MoarVM/MoarVM/commit/6ef4dd3cb1 and https://github.com/MoarVM/MoarVM/pull/1727).

Tests have been added to Rakudo (https://github.com/rakudo/rakudo/pull/4408) and Roast (https://github.com/Raku/roast/pull/736).

So I think it is fine to close this issue as resolved.
