### ISSUE TITLE
literals and boxed types do not get unboxed for native types in multies

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5741]
Migrated from [rt.perl.org#129844](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=129844) (status was 'new')

Searchable as RT129844$

**Comment by usev6** [comment]
The link to the IRC logs doesn't work anymore. I think it would be this discussion (with some context further up): https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2016-10-25#l164

> Will close after https://rt-archive.perl.org/perl6//Public/Bug/Display.html?id=128655 is sorted

Since that issue (which lives at https://github.com/Raku/old-issue-tracker/issues/5460 now) is closed, I'll go ahead and close this one as well (as "Won't fix"). Please reopen, if you disagree.
