### ISSUE TITLE
Should Perl 6 be able to untangle the inclusion of the same role from different sources?

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6030]
Migrated from [rt.perl.org#130634](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130634) (status was 'open')

Searchable as RT130634$

**Comment by usev6** [comment]
It looks like this problem has been solved in the meantime.

The code from original bug report doesn't error out anymore.
```
$ ./rakudo-m -e 'role Alpha { token alpha { :i <[A..Z]> } }; role Digit { token digit { <[0..9]> } }; role Either does Alpha does Digit { token either { <alpha> | <digit> } }; grammar Thingy does Either does Alpha { token TOP { <alpha> <either>* } }; my $match = Thingy.parse("1a3"); dd $match'
Any $match = Any
```

The result looks reasonable, because the parsed string starts with a digit. Parsing ```"b1a3"``` matches more (please note, that I use ```say``` instead of ```dd``` to get a nicer output for this issue):
```
$ ./rakudo-m -e 'role Alpha { token alpha { :i <[A..Z]> } }; role Digit { token digit { <[0..9]> } }; role Either does Alpha does Digit { token either { <alpha> | <digit> } }; grammar Thingy does Either does Alpha { token TOP { <alpha> <either>* } }; my $match = Thingy.parse("b1a3"); say $match'
｢b1a3｣
 alpha => ｢b｣
 either => ｢1｣
  digit => ｢1｣
 either => ｢a｣
  alpha => ｢a｣
 either => ｢3｣
  digit => ｢3｣
```

The golfed code also works as expected:
```
$ ./rakudo-m -e 'role A { method m { 42.say } }; role B does A {}; class C does A does B {}; C.new.m()'
42
$ ./rakudo-m -e 'role A { has $.a = 42 }; role B does A {}; class C does A does B {}; C.new.a.say'
42
```

For the record a working link for the discussion mentioned above: https://colabti.org/irclogger/irclogger_log/perl6?date=2017-01-24#l795

If I understand correctly this has been fixed by @vrurg: https://blogs.perl.org/users/vadim_belman/2019/12/post.html (search for "diamond consumption"). The OP also linked to this blog post [in the Stackoverflow post](https://stackoverflow.com/questions/41791602/should-perl-6-be-able-to-untangle-the-inclusion-of-the-same-role-from-different#comment104959650_41791602).

If I'm not mistaken the bug reported in this issue is covered by the following test in roast: https://github.com/Raku/roast/blob/35456a1a68/S14-roles/composition.t#L77-L83. So I'm going to close the issue without adding another test. (Please reopen if I'm wrong and we need more tests.)
