### ISSUE TITLE
uint attributes behave like int

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6190]
Migrated from [rt.perl.org#131149](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131149) (status was 'new')

Searchable as RT131149$

**Comment by usev6** [comment]
From what I understand this problem is fixed by now:
```
$ ./rakudo-m -e 'say class { has uint $.x }.new: :x(2**64-2)'
<anon|1>.new(x => 18446744073709551614)
```

@niner did some major rework for uints, which no longer behave like ints. That rework certainly also fixed this particular problem. Since there were other tickets (e.g. https://github.com/Raku/old-issue-tracker/issues/3740) and since a lot of tests have been unfudged recently, I'm going to close this one.
