### ISSUE TITLE
When reading from stdin, eof is not respected

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6288]
Migrated from [rt.perl.org#131393](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131393) (status was 'open')

Searchable as RT131393$

**Comment by usev6** [comment]
If I'm not mistaken, the remaining problem has nothing to do with ```eof``` not being respected. Instead the underlying problem seems to be, that connecting the stdout of one (asynchronously started) process to the stdin of another such process doesn't work on the JVM backend due to missing support for access to native file descriptors -- as described in: https://github.com/rakudo/rakudo/issues/1899.

Since the main problem is fixed, I'm closing this old issue.
