### ISSUE TITLE
Coercion type apparently does not check the actual type of the coerced value

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6656]
Migrated from [rt.perl.org#132980](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=132980) (status was 'open')

Searchable as RT132980$

**Comment by raiph** [comment]
Quoting brian's opening comment:

```
class Foo {
  method Int ( --> Str ) { 'Hello' }
  }

  put try-it( Foo.new );

  sub try-it ( Int() $n ) { "Got <$n> of type <{$n.^name}>" }
```

> Although the subroutine signature demanded an `Int`, it accepted
something that claimed to be able to convert but actually didn't​:

> `Got <Hello> of type <Str>`

> I would have expected the runtime constraint to check the ultimate
value against the type and this would have failed.

In recent Rakudos the above code displays:

```
Impossible coercion from 'Foo' into 'Int': method Int returned an instance of Str
```

**Comment by lizmat** [comment]
So it would appear this can be closed?

**Comment by raiph** [comment]
Quoting zoffix's last comment:

> Re-opening this, as there's a much more common case where a typecheck of the coercion result would be desired and that's when coercion results in a Failure​:

```
  <Zoffix_> m​: multi sub foo(Int() $) { }; foo Inf
  <camelia> rakudo-moar 5a6ff4073​: ( no output )
```

That this works without an error is consistent with how the rest of Raku works. For example:

```
my Int() $foo := Failure.new: 'a';
```
silently works, as intended. This is the point of `Failure`s, which the doc describes as "Delayed exception". So this is arguably not a problem.

`Failure`s can be promoted to immediate exceptions:

```
use fatal;
my Int() $foo := Failure.new: 'a';
```

displays:

```
a
  in block <unit> at main.raku line 2
```

So perhaps this issue should be closed.

**Comment by lizmat** [comment]
Thanks for the headsup!

**Comment by raiph** [comment]
I do wonder if this should promote the failure to an immediate exception:
```
my Int:D() $foo := Failure.new: 'a';
```

(One of the reasons I'm revisiting this issue is I'm pondering the whole `Nil` / `Hole` thing. My initial sense was that `Hole` was better, but your advocacy for `Nil` is forcing me to properly justify adding yet another special value, and that's pulling me toward just using `Nil`. But something doesn't smell right, and the `:D` case is something I'm looking at atm.)

While I really like the way Raku type objects play the role other PLs assign to Maybe aka Option, it feels like explicitly specifying a `:D` type smiley is about being explicitly strict, and in that context it currently feels to me like `Failure`s ought perhaps be auto-promoted to being fatal (unless there's an explicit `no fatal` in effect?), and `Nil`s ought resolve to whatever default, and, if that default isn't acceptable, then throw.
