### ISSUE TITLE
MoarVM build fail on termux/Android 6.0.1

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6669]
Migrated from [rt.perl.org#132785](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=132785) (status was 'new')

Searchable as RT132785$

**Comment by tinmarino** [comment]
The issue is with libuv io that need a special treatment (i.e. [patch](https://github.com/termux/termux-packages/tree/master/packages/libuv)) on android. As stated in [nodejs termux package](https://github.com/termux/termux-packages/issues/219) and [uvloop](https://github.com/MagicStack/uvloop/issues/260).
The current state is that MoarVm is announcing it `doesn't know a way to install libuv`. The system installation does not work because it misses `-fPIC` in my Termux install. But manually installing the termux libuv package (with apply the patch), recompiling the sources and moving it in `3dparty` works !

**Comment by JJ** [comment]
This is a MoarVM issue, and @tinmarino provides a solution to it. So I'm closing.
