### ISSUE TITLE
perl 6 parser bugging out on a comment thinking it is a real var

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6691]
Migrated from [rt.perl.org#133791](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=133791) (status was 'open')

Searchable as RT133791$

**Comment by JJ** [comment]
Not sure this is an actual issue? It seems to work as expected, right?

**Comment by AlexDaniel** [comment]
@JJ not really, it is still an issue because rakudo doesn't indicate that it is parsing a string. Basically: `say “foo ; # $bar`. User forgot to close the string and the parser tripped over something that looks like a variable.

**Comment by JJ** [comment]
Again, this seems to be an issue of ordering. It's interpreting the string before checking out if it's finished or not. It's got nothing to do with it having a semicolon or a comment. 

    say “foo $bar

This does exactly the same. And I think this is simply a call. Even if the quotes are closed, this is going to fail, so it probably makes sense to fail as soon as possible"

**Comment by AlexDaniel** [comment]
@JJ not really, it is still an issue because rakudo doesn't indicate that it is parsing a string. Basically: `say “foo ; # $bar`. User forgot to close the string and the parser tripped over something that looks like a variable.

**Comment by JJ** [comment]
@AlexDaniel it's got nothing to do with ; or #. 

    say "$bar

also fails. Again, it's a matter of interpretation, and it seems to me it's a judgement call. The compiler does not care if the user failed to close the string or not. Even if that was the case, $bar is going to fail because it's not defined. So, judgement call, and an example of failing as soon as possible. is there any directive anywhere that says that some syntax errors should have precedence over others?

**Comment by AlexDaniel** [comment]
@JJ I don't know how else I can explain this. The main issue here is that otherwise valid code results in very confusing (LTA) error messages when the user forgets to close their strings.

For example:
```
say “foo ; my $x
```
Trips on $x saying it should be declared first, even though the code is attempting to do just that.

Or:
```
say “foo ; # $x
```
The variable here is part of the comment, so it should be ignored, yet the compiler has no idea because it is still parsing a string.

Yeah, of course, there is a syntax error, no doubt there. But the compiler is producing an error message much, much later, possibly a few lines below, and it *does not* indicate in any way that it was parsing a string when it happened.

**Comment by JJ** [comment]
@AlexDaniel the obverse is also true. You're saying that when there's a semicolon in a string, the compiler should somehow infer that maybe the intention was to close quotes before that. That's simply wrong, and could lead to all kind of problems. In general, interpreting things inside a string as intentions to do anything at all is a slippery slope that will cause many problems (and in any case general slowness).
You say that

    say “foo ; # $x

should be interpreted as an unfinished string (and right before the colon). But what about this?

    say "foo #my $x"

Should we interpret here that there's also a semicolon missing? In general, should we test-compile every string looking for possible syntax errors? In the example, there's a CR in the middle; but CRs are also valid part of strings. Why should there be a difference? Why does the presence of a $ magically turns a string into something that, maybe, is an example of code beyond a non-closed quote? What about this one

    say "this; or maybe $that; this is a hash -> #;

Where should the compiler close the quote? I mean, clearly therein lies dragons.

Let's assume that what is within a string is intended to be within a string, and let's just fail if there's something inside it that's a possible syntax error, like a variable. It's a judgment call, and it's the right one far as I'm concerned.

I agree that the message is LTA. But an error is something the compiler has not understood real well. Ascertaining the intention of the user would mean using certain heuristics (there's one or several CRs; there's one or several ; or maybe }) which would make the error message marginally better and would certainly make it heavier to process after the error, backtracking to try and find stuff... 

So, again, probably we should close this.

**Comment by AlexDaniel** [comment]
> I agree that the message is LTA

Yes. This ticket is marked as LTA.

> So, again, probably we should close this.

What?

The error message should indicate whether the compiler was parsing a string when the compile-time error happened. As simple as that.

**Comment by JJ** [comment]
> > I agree that the message is LTA
> 
> Yes. This ticket is marked as LTA.
> 
> > So, again, probably we should close this.
> 
> What?
> 
> The error message should indicate whether the compiler was parsing a string when the compile-time error happened. As simple as that.

That makes sense...

**Comment by JJ** [comment]
This seems to be a LHF: it needs to change and message and/or fail earlier. Anyone?

**Comment by raiph** [comment]
Addressed by https://github.com/rakudo/rakudo/issues/1475.
